name: Generate Release Package

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create release package
        run: |
          zip -r simple-ci-flask-app.zip .

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: simple-ci-flask-app.zip
